# Generated by Django 3.2 on 2021-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ch', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('xueyuan', models.CharField(blank=True, max_length=100)),
                ('zhuanye', models.CharField(blank=True, max_length=100)),
                ('xuehao', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('laoshi', models.CharField(blank=True, max_length=100)),
                ('riqi', models.DateField()),
                ('wendang', models.FileField(upload_to='file/')),
            ],
        ),
    ]
