# Generated by Django 3.2 on 2021-04-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210416_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliography', models.TextField(blank=True, max_length=300)),
                ('acknowledgment', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
