# Generated by Django 3.2 on 2021-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paperafter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinfo',
            name='abstract_ch',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='abstractinfo',
            name='abstract_en',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paperafter',
            name='acknowledgment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paperafter',
            name='bibliography',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
