# Generated by Django 3.2 on 2021-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210417_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField(blank=True, max_length=1000)),
                ('content2', models.TextField(blank=True, max_length=1000)),
                ('content3', models.TextField(blank=True, max_length=1000)),
                ('content4', models.TextField(blank=True, max_length=1000)),
                ('content5', models.TextField(blank=True, max_length=1000)),
                ('content6', models.TextField(blank=True, max_length=1000)),
                ('content7', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='AbstractInfo',
        ),
        migrations.AddField(
            model_name='authorinfo',
            name='chapternum',
            field=models.IntegerField(default=3),
        ),
    ]
