# Generated by Django 3.2 on 2021-05-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210505_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorinfo',
            name='chapternum',
        ),
    ]
