# Generated by Django 3.2 on 2021-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_authorinfo_chapternum'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinfo',
            name='outputname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
