# Generated by Django 3.2 on 2021-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_abstractinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinfo',
            name='abstract_ch',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='abstractinfo',
            name='abstract_en',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content1',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content4',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content5',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content6',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='contentinfo',
            name='content7',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
